[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "canvas-2"
# The game's title. This will show up in the tile bar of your executable.
title = "canvas-2"
version = "0.1.0"
authors = ["My Name <todo@example.com>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "4.4"
edition = "pro"

[dependencies]
arby = "/Users/sakif/Documents/dragonruby/horde/arby"
rspec-mruby = "/Users/sakif/Documents/dragonruby/horde/rspec-mruby"
inline-require = "/Users/sakif/Documents/dragonruby/horde/inline-require"
pushy = "/Users/sakif/Documents/dragonruby/horde/pushy"
visual-primitives = "/Users/sakif/Documents/dragonruby/horde/visual-primitives"
node-push-layout = "/Users/sakif/Documents/dragonruby/horde/node-push-layout"
ticklish = "/Users/sakif/Documents/dragonruby/horde/ticklish"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "todo-change-me"
# Your username on Itch.io.
username = "todo-change-me"
