[package]
name = "visual-primitives"
authors = ["TODO <TODO@example.com>"]
version = "0.1.0"
homepage = "TODO: Package Website"
keywords = []

# Optional:
# documentation = "https://example.com"
# repository = "http://github.com/example/example"

# Which files do you want to be automatically required from your package.
requires = ["smaug/visual-primitives/require-in-smaug.rb"]

[dependencies]
arby = "/Users/sakif/Documents/dragonruby/horde/arby"
rspec-mruby = "/Users/sakif/Documents/dragonruby/horde/rspec-mruby"
inline-require = "/Users/sakif/Documents/dragonruby/horde/inline-require"
pushy = "/Users/sakif/Documents/dragonruby/horde/pushy"
mruby-ostruct = "/Users/sakif/Documents/dragonruby/horde/mruby-ostruct"
ticklish = "/Users/sakif/Documents/dragonruby/horde/ticklish"


[package.installs]
# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"
"config/web_colors.csv" = "config/web_colors.csv"

[dragonruby]
version = "2"
edition = "standard"
